### ISSUE TITLE
With Kaoto UI 0.6.0, Config panel error: Class constructor JSONSchemaBridge cannot be invoked without 'new'

### ISSUE THREAD

**Issue by apupier** [KaotoIO/vscode-kaoto#115]
`Class constructor JSONSchemaBridge cannot be invoked without 'new'`

![image](https://user-images.githubusercontent.com/1105127/214625460-da4bfba9-adf8-4d3b-877f-0ed22d9980b4.png)

![image](https://user-images.githubusercontent.com/1105127/214625793-c2fce045-3e35-40a2-9193-330b71e11a2c.png)

```
CustomJsonSchemaBridge.tsx:31 Uncaught TypeError: Class constructor JSONSchemaBridge cannot be invoked without 'new'
    at new CustomJsonSchemaBridge (CustomJsonSchemaBridge.tsx:31:5)
    at JsonSchemaConfigurator (JsonSchemaConfigurator.tsx:36:18)
    at renderWithHooks (react-dom.development.js:16305:1)
    at mountIndeterminateComponent (react-dom.development.js:20074:1)
    at beginWork (react-dom.development.js:21587:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4164:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:1)
    at invokeGuardedCallback (react-dom.development.js:4277:1)
    at beginWork$1 (react-dom.development.js:27451:1)
    at performUnitOfWork (react-dom.development.js:26560:1)
    at workLoopSync (react-dom.development.js:26466:1)
    at renderRootSync (react-dom.development.js:26434:1)
    at performSyncWorkOnRoot (react-dom.development.js:26085:1)
    at flushSyncCallbacks (react-dom.development.js:12042:1)
    at flushSyncCallbacksOnlyInLegacyMode (react-dom.development.js:12021:1)
    at batchedUpdates$1 (react-dom.development.js:26148:1)
    at batchedUpdates (react-dom.development.js:3991:1)
    at dispatchEventForPluginEventSystem (react-dom.development.js:9287:1) 
```

**Comment by apupier** [comment]
Found several references that are mentioning to change the target in tsconfig file to es6+ but still same error
