### ISSUE TITLE
Fix issue related to flaky test on MacOS

### ISSUE THREAD

**Issue by apupier** [KaotoIO/vscode-kaoto#122]
Since upgrade to Kaoto 0.6.1, the test is failing very often on MacOS with GitHub Actions

**Comment by apupier** [comment]
```
1) Kaoto basic development flow
       Open "empty.kaoto.yaml" file and check Kaoto UI is loading:
     Error: Timeout of 50000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/Users/runner/work/vscode-kaoto/vscode-kaoto/out/BasicFlow.test.js)
      at listOnTimeout (node:internal/timers:559:17)
      at processTimers (node:internal/timers:502:7)

  2) Kaoto basic development flow
       "after all" hook for "Open "empty.kaoto.yaml" file and check Kaoto UI is loading":
     StaleElementReferenceError: stale element reference: element is not attached to the page document
  (Session info: chrome=102.0.[50](https://github.com/KaotoIO/vscode-kaoto/actions/runs/4023154356/jobs/6913681418#step:8:51)05.167)
      at Object.throwDecodedError (node_modules/selenium-webdriver/lib/error.js:524:15)
      at parseHttpResponse (node_modules/selenium-webdriver/lib/http.js:587:13)
      at Executor.execute (node_modules/selenium-webdriver/lib/http.js:[51](https://github.com/KaotoIO/vscode-kaoto/actions/runs/4023154356/jobs/6913681418#step:8:52)5:28)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async Driver.execute (node_modules/selenium-webdriver/lib/webdriver.js:741:17)
```
