### ISSUE TITLE
`query.toLowerCase is not a function` with main kaoto-ui branch when using search field of contextual catalog

### ISSUE THREAD

**Issue by apupier** [KaotoIO/vscode-kaoto#135]
maybe only a matter of aligning some dependencies?

```
MiniCatalog.tsx:91 Uncaught TypeError: query.toLowerCase is not a function
    at MiniCatalog.tsx:91:54
    at Array.filter (<anonymous>)
    at search (MiniCatalog.tsx:89:18)
    at MiniCatalog (MiniCatalog.tsx:161:15)
    at renderWithHooks (react-dom.development.js:16305:1)
    at updateFunctionComponent (react-dom.development.js:19588:1)
    at beginWork (react-dom.development.js:21601:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4164:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:1)
    at invokeGuardedCallback (react-dom.development.js:4277:1)
    at beginWork$1 (react-dom.development.js:27451:1)
    at performUnitOfWork (react-dom.development.js:26560:1)
    at workLoopSync (react-dom.development.js:26466:1)
    at renderRootSync (react-dom.development.js:26434:1)
    at performSyncWorkOnRoot (react-dom.development.js:26085:1)
    at flushSyncCallbacks (react-dom.development.js:12042:1)
    at flushSyncCallbacksOnlyInLegacyMode (react-dom.development.js:12021:1)
    at batchedUpdates$1 (react-dom.development.js:26148:1)
    at batchedUpdates (react-dom.development.js:3991:1)
    at dispatchEventForPluginEventSystem (react-dom.development.js:9287:1)
    at dispatchEventWithEnableCapturePhaseSelectiveHydrationWithoutDiscreteEventReplay (react-dom.development.js:6465:1)
    at dispatchEvent (react-dom.development.js:6457:1)
    at dispatchDiscreteEvent (react-dom.development.js:6430:1)
 ```

![image](https://user-images.githubusercontent.com/1105127/220146373-4739b900-917d-4e38-a9b0-bedbfc7158d9.png)

**Comment by apupier** [comment]
aligning @patternfly/react-core version to the one from Kaoto UI is fixing the problem so will be covered when upgrading to release of Sprint 15 of Kaoto UI
