### ISSUE TITLE
Choice config tab is not working with Kaoto 0.7.0 `Cannot read properties of null (reading 'useState')`

### ISSUE THREAD

**Issue by apupier** [KaotoIO/vscode-kaoto#157]
![image](https://user-images.githubusercontent.com/1105127/221899424-9ec81876-20f9-4ee3-9fc4-37b7ecc7eb25.png)

**Comment by apupier** [comment]
```
Uncaught TypeError: Cannot read properties of null (reading 'useState')
    at t.useState (react.production.min.js:25:394)
    at a (ChoiceStep.tsx:29:27)
    at renderWithHooks (react-dom.development.js:16305:1)
    at updateFunctionComponent (react-dom.development.js:19588:1)
    at mountLazyComponent (react-dom.development.js:19959:1)
    at beginWork (react-dom.development.js:21593:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4164:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:1)
    at invokeGuardedCallback (react-dom.development.js:4277:1)
    at beginWork$1 (react-dom.development.js:27451:1)
    at performUnitOfWork (react-dom.development.js:26560:1)
    at workLoopSync (react-dom.development.js:26466:1)
    at renderRootSync (react-dom.development.js:26434:1)
    at performSyncWorkOnRoot (react-dom.development.js:26085:1)
    at flushSyncCallbacks (react-dom.development.js:12042:1)
    at react-dom.development.js:25651:1
```

```
The above error occurred in the <a> component:

    at a (https://kaotoio.github.io/step-extension-repository/choice/8.js:1:262)
    at Suspense
    at ErrorBoundary (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:241433:37)
    at StepErrorBoundary (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:5376:30)
    at Extension (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:4504:13)
    at ErrorBoundary (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:241433:37)
    at StepErrorBoundary (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:5376:30)
    at section
    at TabContentBase (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:25837:11)
    at Tabs (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:25942:9)
    at div
    at DrawerPanelBody (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:19408:5)
    at VisualizationStepViews (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:5752:35)
    at div
    at div
    at GenerateId (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:28284:9)
    at DrawerPanelContent (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:19445:11)
    at div
    at DrawerMain (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:19377:5)
    at DrawerContent (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:19278:5)
    at div
    at Drawer (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:19172:11)
    at KaotoDrawer (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:4634:11)
    at ErrorBoundary (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:241433:37)
    at StepErrorBoundary (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:5376:30)
    at Visualization (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:5467:98)
    at ReactFlowProvider (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:50715:30)
    at div
    at DrawerContentBody (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:19312:5)
    at div
    at div
    at DrawerMain (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:19377:5)
    at DrawerContent (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:19278:5)
    at div
    at Drawer (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:19172:11)
    at KaotoDrawer (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:4634:11)
    at section
    at PageSection (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:22708:11)
    at main
    at div
    at Page (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:22397:9)
    at div
    at FlexItem (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:32537:11)
    at div
    at Flex (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:32503:11)
    at div
    at DrawerContentBody (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:19312:5)
    at div
    at div
    at DrawerMain (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:19377:5)
    at DrawerContent (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:19278:5)
    at div
    at Drawer (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:19172:11)
    at KaotoDrawer (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:4634:11)
    at Dashboard (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:6506:108)
    at Route (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:243619:29)
    at RouteWithTitleUpdates (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:6837:22)
    at Switch (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:243821:29)
    at LastLocationProvider (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:242751:47)
    at C (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:243876:37)
    at AppRoutes
    at div
    at PanelBase (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:22747:11)
    at Panel
    at AppLayout (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:6436:22)
    at Suspense
    at Router (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:243238:30)
    at HashRouter (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:242333:35)
    at AlertProvider (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:6630:26)
    at KogitoEditorIntegrationProviderInternal (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:6236:52)
    at https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:6034:94
    at div
    at EditorEnvelopeViewRef (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:14513:42)
    at I18nDictionariesProvider (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:16433:55)

React will try to recreate this component tree from scratch using the error boundary you provided, ErrorBoundary.
```

**Comment by apupier** [comment]
reproducing with Set property and set header so I suppose all Step extensions are affected

**Comment by apupier** [comment]
error reproduced with:
d40f3774394dc4c74d485f2b6e85a2f66b73f140

Working fine with:
97f3d25d4ef7661b0a2bc5287d705fc4bd549b54
