### ISSUE TITLE
Cannot add a string property on a beans configuration (main Kaoto UI branch)

### ISSUE THREAD

**Issue by apupier** [KaotoIO/vscode-kaoto#283]
https://github.com/KaotoIO/vscode-kaoto/assets/1105127/bfb99b50-dc17-4356-b27e-ba2c22e9e67b

![image](https://github.com/KaotoIO/vscode-kaoto/assets/1105127/868d98f9-9629-4607-a4ce-9cd61b2e0c8f)

in console:
```
Uncaught TypeError: Cannot convert undefined or null to object
    at Function.entries (<anonymous>)
    at Properties (PropertiesField.tsx:185:39)
    at renderWithHooks (react-dom.development.js:16305:1)
    at updateFunctionComponent (react-dom.development.js:19588:1)
    at beginWork (react-dom.development.js:21601:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4164:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:1)
    at invokeGuardedCallback (react-dom.development.js:4277:1)
    at beginWork$1 (react-dom.development.js:27451:1)
    at performUnitOfWork (react-dom.development.js:26560:1)
 ```
```
The above error occurred in the <Properties> component:

    at Properties (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:8113:94)
    at Field (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:186413:97)
    at AutoField (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:186473:96)
    at div
    at AutoFields (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:14138:11)
    at form
    at FormBase (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:226745:11)
    at Form
    at AutoValidatedQuickPatternflyForm
    at div
    at StackItem (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:225541:11)
    at div
    at Stack (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:225511:11)
    at div
    at SplitItem (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:225462:11)
    at div
    at Split (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:225432:11)
    at ErrorBoundary (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:182753:5)
    at StepErrorBoundary (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:7161:30)
    at div
    at ModalBoxBody (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:207180:11)
    at div
    at ModalBox (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:207147:11)
    at div
    at FocusTrapBase (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:220109:9)
    at div
    at Backdrop (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:196403:11)
    at ModalContent (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:207419:11)
    at Modal (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:207005:9)
    at MetadataEditorModal (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:7956:32)
    at div
    at ToolbarItem (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:217843:11)
    at MetadataToolbarItems (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:8045:73)
    at div
    at div
    at ToolbarContent (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:217562:9)
    at div
    at GenerateId (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:220201:9)
    at Toolbar (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:217394:9)
    at KaotoToolbar (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:6576:25)
    at section
    at PageSection (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:210258:11)
    at main
    at div
    at Page (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:209744:9)
    at div
    at FlexItem (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:225096:11)
    at div
    at Flex (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:225062:11)
    at div
    at DrawerContentBody (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:200460:5)
    at div
    at div
    at DrawerMain (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:200525:5)
    at DrawerContent (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:200426:5)
    at div
    at Drawer (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:200320:11)
    at KaotoDrawer (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:6505:11)
    at Dashboard (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:9144:108)
    at Route (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:184886:29)
    at RouteWithTitleUpdates (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:9469:22)
    at Switch (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:185088:29)
    at LastLocationProvider (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:184018:47)
    at C (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:185143:37)
    at AppRoutes
    at div
    at PanelBase (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:210940:11)
    at Panel
    at AppLayout (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:9069:22)
    at Suspense
    at Router (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:184505:30)
    at HashRouter (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:183600:35)
    at AlertProvider (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:9265:26)
    at KogitoEditorIntegrationProviderInternal (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:8850:52)
    at https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:8635:94
    at div
    at EditorEnvelopeViewRef (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:191648:42)
    at I18nDictionariesProvider (https://file+.vscode-resource.vscode-cdn.net/home/apupier/git/vscode-kaoto/dist/webview/KaotoEditorEnvelopeApp.js:193405:55)

React will try to recreate this component tree from scratch using the error boundary you provided, ErrorBoundary.
```

**Comment by apupier** [comment]
worth checking that depdencies versions are aligned, especially for Patternfly

**Comment by igarashitm** [comment]
reopening - @apupier already hit another bug on beans editor, to be investigated

**Comment by igarashitm** [comment]
Closing, we'll continue on #284
