### ISSUE TITLE
Cannot read properties of undefined (reading 'name') in KogitoEditorIntegrationProvider.tsx:49:38 with kaoto UI main branch

### ISSUE THREAD

**Issue by apupier** [KaotoIO/vscode-kaoto#293]
With some integration files, there is a blank page.

Example of files to reproduce:
```
apiVersion: camel.apache.org/v1alpha1
kind: KameletBinding
metadata:
  name: my-integration-name
spec: {}
```

stacjktrace in console:
```
KogitoEditorIntegrationProvider.tsx:49 Uncaught TypeError: Cannot read properties of undefined (reading 'name')
    at KogitoEditorIntegrationProvider.tsx:49:38
    at memoizedSelector (with-selector.development.js:79:1)
    at getSnapshotWithSelector (with-selector.development.js:134:1)
    at updateSyncExternalStore (react-dom.development.js:16860:1)
    at Object.useSyncExternalStore (react-dom.development.js:17943:1)
    at useSyncExternalStore (react.development.js:1676:1)
    at useSyncExternalStoreWithSelector (with-selector.development.js:145:1)
    at useStore (index.mjs:8:1)
    at useBoundStore (index.mjs:25:1)
    at KogitoEditorIntegrationProviderInternal (KogitoEditorIntegrationProvider.tsx:47:80)
```

**Comment by apupier** [comment]
the stack is pointing to code that was chnanged very recently in this PR https://github.com/KaotoIO/kaoto-ui/pull/2034/
