### ISSUE TITLE
Kaoto API is unreachable

### ISSUE THREAD

**Issue by imod** [KaotoIO/vscode-kaoto#382]
I run the following version on my Mac:

`VS Code Extension Kaoto v0.10.0`

on VS Code:
```
Version: 1.83.1 (Universal)
Commit: f1b07bd25dfad64b0167beb15359ae573aecd2cc
Date: 2023-10-10T23:46:55.789Z (1 wk ago)
Electron: 25.8.4
ElectronBuildId: 24154031
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin x64 21.6.0
```

I create a file calles `demo.camel.yaml' and all I get is this error: "Kaoto API is unreachable"

I also checked whether the backend port is used at all: `lsof -i :8097` - but its not used by any process, so I guess the backend is not even started/running...

<img width="828" alt="Screenshot 2023-10-19 at 15 32 47" src="https://github.com/KaotoIO/vscode-kaoto/assets/543297/76e0d4db-0031-42a2-91d8-91502f3fec12">

**Comment by lordrip** [comment]
Hi @imod, could you please share the content of the `Output` pane, at the Kaoto channel?

One way to do it could be by pressing `Cmd + Shift + P` and selecting `Output: Show Output Channels...` and selecting `Kaoto` from the dropdown.

![image](https://github.com/KaotoIO/vscode-kaoto/assets/16512618/b2321f2b-a46f-4c6e-8761-d1922c4b6d75)

**Comment by imod** [comment]
Hey @lordrip, this is what I get:

```
__  ____  __  _____   ___  __ ____  ______ 
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
2023-10-19 15:42:48,280 INFO  [io.kao.bac.api.met.cat.AbstractCatalog] (ForkJoinPool.commonPool-worker-1) Parser class io.kaoto.backend.metadata.parser.JarParseCatalog processed in 10ms.
2023-10-19 15:42:48,287 INFO  [io.kao.bac.api.met.cat.AbstractCatalog] (ForkJoinPool.commonPool-worker-1) Catalog class io.kaoto.backend.api.metadata.catalog.ViewDefinitionCatalog_Subclass warmed up in 17ms.
2023-10-19 15:42:48,371 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main) Apache Camel 4.0.0 (camel-1) is shutting down
2023-10-19 15:42:48,373 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main) Routes stopped (stopped:0)
2023-10-19 15:42:48,376 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main) Apache Camel 4.0.0 (camel-1) shutdown in 6ms (uptime:)
2023-10-19 15:42:48,768 ERROR [io.qua.run.Application] (main) Failed to start application (with profile [prod]): java.lang.RuntimeException: Failed to start quarkus
	at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
	at io.quarkus.runtime.Application.start(Application.java:101)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:111)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
	at io.kaoto.backend.api.Main.main(Main.java:11)
Caused by: java.lang.RuntimeException: EC Keys are not supported when using the native binary, please add the org.bouncycastle:bcpkix-jdk18on dependency
	at io.fabric8.kubernetes.client.internal.CertUtils.handleECKey(CertUtils.java:15)
	at io.fabric8.kubernetes.client.internal.CertUtils.loadKey(CertUtils.java:141)
	at io.fabric8.kubernetes.client.internal.CertUtils.createKeyStore(CertUtils.java:117)
	at io.fabric8.kubernetes.client.internal.CertUtils.createKeyStore(CertUtils.java:259)
	at io.fabric8.kubernetes.client.internal.SSLUtils.keyManagers(SSLUtils.java:188)
	at io.fabric8.kubernetes.client.internal.SSLUtils.keyManagers(SSLUtils.java:177)
	at io.fabric8.kubernetes.client.utils.HttpClientUtils.applyCommonConfiguration(HttpClientUtils.java:188)
	at io.fabric8.kubernetes.client.http.HttpClient$Factory.newBuilder(HttpClient.java:51)
	at io.quarkus.kubernetes.client.runtime.QuarkusHttpClientFactory.newBuilder(QuarkusHttpClientFactory.java:57)
	at io.fabric8.kubernetes.client.KubernetesClientBuilder.getHttpClient(KubernetesClientBuilder.java:90)
	at io.fabric8.kubernetes.client.KubernetesClientBuilder.build(KubernetesClientBuilder.java:79)
	at io.quarkus.kubernetes.client.runtime.KubernetesClientProducer.kubernetesClient(KubernetesClientProducer.java:23)
	at io.quarkus.kubernetes.client.runtime.KubernetesClientProducer_ProducerMethod_kubernetesClient_425666137c75a3aa53513fc8edf86fe072add6bd_Bean.doCreate(Unknown Source)
	at io.quarkus.kubernetes.client.runtime.KubernetesClientProducer_ProducerMethod_kubernetesClient_425666137c75a3aa53513fc8edf86fe072add6bd_Bean.create(Unknown Source)
	at io.quarkus.kubernetes.client.runtime.KubernetesClientProducer_ProducerMethod_kubernetesClient_425666137c75a3aa53513fc8edf86fe072add6bd_Bean.create(Unknown Source)
	at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:113)
	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:37)
	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:34)
	at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:26)
	at io.quarkus.arc.impl.ComputingCache.computeIfAbsent(ComputingCache.java:69)
	at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:34)
	at io.quarkus.kubernetes.client.runtime.KubernetesClientProducer_ProducerMethod_kubernetesClient_425666137c75a3aa53513fc8edf86fe072add6bd_Bean.get(Unknown Source)
	at io.quarkus.kubernetes.client.runtime.KubernetesClientProducer_ProducerMethod_kubernetesClient_425666137c75a3aa53513fc8edf86fe072add6bd_Bean.get(Unknown Source)
	at io.kaoto.backend.api.metadata.catalog.StepCatalog_Bean.doCreate(Unknown Source)
	at io.kaoto.backend.api.metadata.catalog.StepCatalog_Bean.create(Unknown Source)
	at io.kaoto.backend.api.metadata.catalog.StepCatalog_Bean.create(Unknown Source)
	at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:113)
	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:37)
	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:34)
	at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:26)
	at io.quarkus.arc.impl.ComputingCache.computeIfAbsent(ComputingCache.java:69)
	at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:34)
	at io.quarkus.arc.impl.ClientProxies.getApplicationScopedDelegate(ClientProxies.java:21)
	at io.kaoto.backend.api.metadata.catalog.StepCatalog_ClientProxy.arc$delegate(Unknown Source)
	at io.kaoto.backend.api.metadata.catalog.StepCatalog_ClientProxy.arc_contextualInstance(Unknown Source)
	at io.kaoto.backend.api.metadata.catalog.StepCatalog_Observer_Synthetic_990b63f4ba72c76d78275569111a6a60b17e84a2.notify(Unknown Source)
	at io.quarkus.arc.impl.EventImpl$Notifier.notifyObservers(EventImpl.java:346)
	at io.quarkus.arc.impl.EventImpl$Notifier.notify(EventImpl.java:328)
	at io.quarkus.arc.impl.EventImpl.fire(EventImpl.java:82)
	at io.quarkus.arc.runtime.ArcRecorder.fireLifecycleEvent(ArcRecorder.java:155)
	at io.quarkus.arc.runtime.ArcRecorder.handleLifecycleEvents(ArcRecorder.java:106)
	at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy_0(Unknown Source)
	at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy(Unknown Source)
	... 6 more

Kaoto backend process closed with code: 1
Kaoto backend failed to warm up in 1 minute.
```

**Comment by apupier** [comment]
Hello,

thanks for the report. To help investigating and narrowing down the potential root issues. Can you try with VS Code Kaoto 0.9.0 please? Are you able to reproduce the issue?

**Comment by apupier** [comment]
other idea: are you connected to a Kubernetes/OpenShift instance? If yes, can you precise teh version? Can you precise if kamelets are deployed on it? in which version?using which tool (VS Code, comand-line oc/kubectl, ...). Can you try to disconnect and restart VS Code?

**Comment by imod** [comment]
hey @lordrip , I got the exact same error
...I'm not conntected to any k8s/OS cluster...

```
__  ____  __  _____   ___  __ ____  ______ 
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
2023-10-23 16:39:26,020 INFO  [io.kao.bac.api.met.cat.AbstractCatalog] (ForkJoinPool.commonPool-worker-1) Parser class io.kaoto.backend.metadata.parser.JarParseCatalog processed in 11ms.
2023-10-23 16:39:26,021 INFO  [io.kao.bac.api.met.cat.AbstractCatalog] (ForkJoinPool.commonPool-worker-1) Catalog class io.kaoto.backend.api.metadata.catalog.ViewDefinitionCatalog_Subclass warmed up in 12ms.
2023-10-23 16:39:26,042 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main) Apache Camel 4.0.0 (camel-1) is shutting down
2023-10-23 16:39:26,042 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main) Routes stopped (stopped:0)
2023-10-23 16:39:26,042 INFO  [org.apa.cam.imp.eng.AbstractCamelContext] (main) Apache Camel 4.0.0 (camel-1) shutdown in 1ms (uptime:)
2023-10-23 16:39:26,514 ERROR [io.qua.run.Application] (main) Failed to start application (with profile [prod]): java.lang.RuntimeException: Failed to start quarkus
	at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
	at io.quarkus.runtime.Application.start(Application.java:101)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:111)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
	at io.kaoto.backend.api.Main.main(Main.java:11)
Caused by: java.lang.RuntimeException: EC Keys are not supported when using the native binary, please add the org.bouncycastle:bcpkix-jdk18on dependency
	at io.fabric8.kubernetes.client.internal.CertUtils.handleECKey(CertUtils.java:15)
	at io.fabric8.kubernetes.client.internal.CertUtils.loadKey(CertUtils.java:141)
	at io.fabric8.kubernetes.client.internal.CertUtils.createKeyStore(CertUtils.java:117)
	at io.fabric8.kubernetes.client.internal.CertUtils.createKeyStore(CertUtils.java:259)
	at io.fabric8.kubernetes.client.internal.SSLUtils.keyManagers(SSLUtils.java:188)
	at io.fabric8.kubernetes.client.internal.SSLUtils.keyManagers(SSLUtils.java:177)
	at io.fabric8.kubernetes.client.utils.HttpClientUtils.applyCommonConfiguration(HttpClientUtils.java:188)
	at io.fabric8.kubernetes.client.http.HttpClient$Factory.newBuilder(HttpClient.java:51)
	at io.quarkus.kubernetes.client.runtime.QuarkusHttpClientFactory.newBuilder(QuarkusHttpClientFactory.java:57)
	at io.fabric8.kubernetes.client.KubernetesClientBuilder.getHttpClient(KubernetesClientBuilder.java:90)
	at io.fabric8.kubernetes.client.KubernetesClientBuilder.build(KubernetesClientBuilder.java:79)
	at io.quarkus.kubernetes.client.runtime.KubernetesClientProducer.kubernetesClient(KubernetesClientProducer.java:23)
	at io.quarkus.kubernetes.client.runtime.KubernetesClientProducer_ProducerMethod_kubernetesClient_425666137c75a3aa53513fc8edf86fe072add6bd_Bean.doCreate(Unknown Source)
	at io.quarkus.kubernetes.client.runtime.KubernetesClientProducer_ProducerMethod_kubernetesClient_425666137c75a3aa53513fc8edf86fe072add6bd_Bean.create(Unknown Source)
	at io.quarkus.kubernetes.client.runtime.KubernetesClientProducer_ProducerMethod_kubernetesClient_425666137c75a3aa53513fc8edf86fe072add6bd_Bean.create(Unknown Source)
	at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:113)
	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:37)
	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:34)
	at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:26)
	at io.quarkus.arc.impl.ComputingCache.computeIfAbsent(ComputingCache.java:69)
	at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:34)
	at io.quarkus.kubernetes.client.runtime.KubernetesClientProducer_ProducerMethod_kubernetesClient_425666137c75a3aa53513fc8edf86fe072add6bd_Bean.get(Unknown Source)
	at io.quarkus.kubernetes.client.runtime.KubernetesClientProducer_ProducerMethod_kubernetesClient_425666137c75a3aa53513fc8edf86fe072add6bd_Bean.get(Unknown Source)
	at io.kaoto.backend.api.metadata.catalog.StepCatalog_Bean.doCreate(Unknown Source)
	at io.kaoto.backend.api.metadata.catalog.StepCatalog_Bean.create(Unknown Source)
	at io.kaoto.backend.api.metadata.catalog.StepCatalog_Bean.create(Unknown Source)
	at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:113)
	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:37)
	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:34)
	at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:26)
	at io.quarkus.arc.impl.ComputingCache.computeIfAbsent(ComputingCache.java:69)
	at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:34)
	at io.quarkus.arc.impl.ClientProxies.getApplicationScopedDelegate(ClientProxies.java:21)
	at io.kaoto.backend.api.metadata.catalog.StepCatalog_ClientProxy.arc$delegate(Unknown Source)
	at io.kaoto.backend.api.metadata.catalog.StepCatalog_ClientProxy.arc_contextualInstance(Unknown Source)
	at io.kaoto.backend.api.metadata.catalog.StepCatalog_Observer_Synthetic_990b63f4ba72c76d78275569111a6a60b17e84a2.notify(Unknown Source)
	at io.quarkus.arc.impl.EventImpl$Notifier.notifyObservers(EventImpl.java:346)
	at io.quarkus.arc.impl.EventImpl$Notifier.notify(EventImpl.java:328)
	at io.quarkus.arc.impl.EventImpl.fire(EventImpl.java:82)
	at io.quarkus.arc.runtime.ArcRecorder.fireLifecycleEvent(ArcRecorder.java:155)
	at io.quarkus.arc.runtime.ArcRecorder.handleLifecycleEvents(ArcRecorder.java:106)
	at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy_0(Unknown Source)
	at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy(Unknown Source)
	... 6 more

Kaoto backend process closed with code: 1
```

**Comment by imod** [comment]
@apupier @lordrip any idea how to fix this?

**Comment by lhein** [comment]
While the investigation is ongoing you could also switch to our online version at https://red.ht/kaoto . Maybe this can unblock you for now.

**Comment by apupier** [comment]
we were unable to reproduce unfortunately.
I think we can try to do a "stab in the dark" and follow blindly the hint by adding the dependency on `org.bouncycastle:bcpkix-jdk18on` and give you a version to try.
But it sounds very strange as I spotted some information that this should not be needed for several years now (of course I cannot find again the reference now). Also it is a jar supposed to be needed for JDK 8 and [the compilation is done with Java 17](https://github.com/KaotoIO/kaoto-backend/blob/46d80f820df9eceb564b13ff6c73a742434b9af2/pom.xml#L14)

The good news is that with Kaoto-next, there won't be this problem as there won't be a backend natively compiled

**Comment by lhein** [comment]
Regarding Kaoto-Next...
This is the successor of the current Kaoto v1. It is still being developed but we are close to having the same functionality as Kaoto v1.  You can already take a sneak peek at https://kaotoio.github.io/kaoto-next/#/ and there will be an update to the current VS Code extension to use Kaoto-Next hopefully later this year.

**Comment by apupier** [comment]
Next version of kaoto integrated on main branch and will be available in next release of VS Code kaoto
