### ISSUE TITLE
Several Actions are vanishing when trying to add them: Aggregate, Marshal, set-header...

### ISSUE THREAD

**Issue by apupier** [KaotoIO/vscode-kaoto#46]
it is working fine on standalone version. On VS Code, the step is briefly displayed and then is vanishing

![vanishingStep](https://user-images.githubusercontent.com/1105127/196169940-30cd7eba-559b-494e-8177-18b7279fce19.gif)

in console, there is this message in red:
```json
{
    "requestId": "EnvelopeServer_13",
    "type": "kogitoEditor_contentRequest",
    "data": [],
    "purpose": "request",
    "directSender": "envelopeServer"
}
```

<details>
<summary>Click for full console log when trying to add the step</summary>

```
console.ts:137 [Extension Host] {
  type: 'kogitoWorkspace_newEdit',
  data: [
    {
      id: 'apiVersion: camel.apache.org/v1alpha1\n' +
        'kind: KameletBinding\n' +
        'metadata:\n' +
        '  name: integration\n' +
        'spec:\n' +
        '  source:\n' +
        '    ref:\n' +
        '      apiVersion: camel.apache.org/v1alpha1\n' +
        '      name: webhook-source\n' +
        '      kind: Kamelet\n' +
        '  steps:\n' +
        '  - ref:\n' +
        '      apiVersion: camel.apache.org/v1alpha1\n' +
        '      name: avro-deserialize-action\n' +
        '      kind: Kamelet\n' +
        '  sink:\n' +
        '    ref:\n' +
        '      apiVersion: camel.apache.org/v1alpha1\n' +
        '      name: aggregate\n' +
        '      kind: Kamelet\n'
    }
  ],
  purpose: 'notification',
  targetEnvelopeServerId: '_y36kgk0rf_178',
  directSender: 'envelopeClient'
} (at console.<anonymous> (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:85:94751))
console.ts:137 [Extension Host] {
  type: 'kogitoWorkspace_newEdit',
  data: [
    {
      id: 'apiVersion: camel.apache.org/v1alpha1\n' +
        'kind: KameletBinding\n' +
        'metadata:\n' +
        '  name: integration\n' +
        'spec:\n' +
        '  source:\n' +
        '    ref:\n' +
        '      apiVersion: camel.apache.org/v1alpha1\n' +
        '      name: webhook-source\n' +
        '      kind: Kamelet\n' +
        '  sink:\n' +
        '    ref:\n' +
        '      apiVersion: camel.apache.org/v1alpha1\n' +
        '      name: avro-deserialize-action\n' +
        '      kind: Kamelet\n'
    }
  ],
  purpose: 'notification',
  targetEnvelopeServerId: '_y36kgk0rf_178',
  directSender: 'envelopeClient'
} (at console.<anonymous> (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:85:94751))
localProcessExtensionHost.ts:298 Extension Host
localProcessExtensionHost.ts:299 {
  type: 'kogitoWorkspace_newEdit',
  data: [
    {
      id: 'apiVersion: camel.apache.org/v1alpha1\n' +
        'kind: KameletBinding\n' +
        'metadata:\n' +
        '  name: integration\n' +
        'spec:\n' +
        '  source:\n' +
        '    ref:\n' +
        '      apiVersion: camel.apache.org/v1alpha1\n' +
        '      name: webhook-source\n' +
        '      kind: Kamelet\n' +
        '  steps:\n' +
        '  - ref:\n' +
        '      apiVersion: camel.apache.org/v1alpha1\n' +
        '      name: avro-deserialize-action\n' +
        '      kind: Kamelet\n' +
        '  sink:\n' +
        '    ref:\n' +
        '      apiVersion: camel.apache.org/v1alpha1\n' +
        '      name: aggregate\n' +
        '      kind: Kamelet\n'
    }
  ],
  purpose: 'notification',
  targetEnvelopeServerId: '_y36kgk0rf_178',
  directSender: 'envelopeClient'
}
{
  type: 'kogitoWorkspace_newEdit',
  data: [
    {
      id: 'apiVersion: camel.apache.org/v1alpha1\n' +
        'kind: KameletBinding\n' +
        'metadata:\n' +
        '  name: integration\n' +
        'spec:\n' +
        '  source:\n' +
        '    ref:\n' +
        '      apiVersion: camel.apache.org/v1alpha1\n' +
        '      name: webhook-source\n' +
        '      kind: Kamelet\n' +
        '  sink:\n' +
        '    ref:\n' +
        '      apiVersion: camel.apache.org/v1alpha1\n' +
        '      name: avro-deserialize-action\n' +
        '      kind: Kamelet\n'
    }
  ],
  purpose: 'notification',
  targetEnvelopeServerId: '_y36kgk0rf_178',
  directSender: 'envelopeClient'
}

KaotoEditorEnvelopeApp.js:8 {requestId: 'EnvelopeServer_16', type: 'kogitoEditor_contentRequest', data: Array(0), purpose: 'request', directSender: 'envelopeServer'}
console.ts:137 [Extension Host] {
  requestId: 'EnvelopeServer_16',
  purpose: 'response',
  type: 'kogitoEditor_contentRequest',
  data: {
    content: 'apiVersion: camel.apache.org/v1alpha1\n' +
      'kind: KameletBinding\n' +
      'metadata:\n' +
      '  name: integration\n' +
      'spec:\n' +
      '  source:\n' +
      '    ref:\n' +
      '      apiVersion: camel.apache.org/v1alpha1\n' +
      '      name: webhook-source\n' +
      '      kind: Kamelet\n' +
      '  sink:\n' +
      '    ref:\n' +
      '      apiVersion: camel.apache.org/v1alpha1\n' +
      '      name: avro-deserialize-action\n' +
      '      kind: Kamelet\n'
  },
  targetEnvelopeServerId: '_y36kgk0rf_178',
  directSender: 'envelopeClient'
} (at console.<anonymous> (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:85:94751))
console.ts:137 [Extension Host] Backup saved. (at console.<anonymous> (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:85:94751))
localProcessExtensionHost.ts:298 Extension Host
localProcessExtensionHost.ts:299 {
  requestId: 'EnvelopeServer_16',
  purpose: 'response',
  type: 'kogitoEditor_contentRequest',
  data: {
    content: 'apiVersion: camel.apache.org/v1alpha1\n' +
      'kind: KameletBinding\n' +
      'metadata:\n' +
      '  name: integration\n' +
      'spec:\n' +
      '  source:\n' +
      '    ref:\n' +
      '      apiVersion: camel.apache.org/v1alpha1\n' +
      '      name: webhook-source\n' +
      '      kind: Kamelet\n' +
      '  sink:\n' +
      '    ref:\n' +
      '      apiVersion: camel.apache.org/v1alpha1\n' +
      '      name: avro-deserialize-action\n' +
      '      kind: Kamelet\n'
  },
  targetEnvelopeServerId: '_y36kgk0rf_178',
  directSender: 'envelopeClient'
}

console.ts:137 [Extension Host] {
    "kind": "Config",
    "apiVersion": "v1",
    "preferences": {},
    "clusters": [
        {
            "name": "api-crc-testing:6443",
            "cluster": {
                "server": "https://api.crc.testing:6443",
                "certificate-authority-data": "DATA+OMITTED"
            }
        }
    ],
    "users": [
        {
            "name": "developer",
            "user": {
                "token": "REDACTED"
            }
        },
        {
            "name": "developer/api-crc-testing:6443",
            "user": {
                "token": "REDACTED"
            }
        },
        {
            "name": "kube:admin",
            "user": {
                "token": "REDACTED"
            }
        },
        {
            "name": "kubeadmin",
            "user": {
                "token": "REDACTED"
            }
        },
        {
            "name": "kubeadmin/api-crc-testing:6443",
            "user": {
                "token": "REDACTED"
            }
        }
    ],
    "contexts": [
        {
            "name": "/api-crc-testing:6443/developer",
            "context": {
                "cluster": "api-crc-testing:6443",
                "user": "developer/api-crc-testing:6443"
            }
        },
        {
            "name": "crc-admin",
            "context": {
                "cluster": "api-crc-testing:6443",
                "user": "kubeadmin",
                "namespace": "default"
            }
        },
        {
            "name": "crc-developer",
            "context": {
                "cluster": "api-crc-testing:6443",
                "user": "developer",
                "namespace": "default"
            }
        },
        {
            "name": "default/api-crc-testing:6443/kubeadmin",
            "context": {
                "cluster": "api-crc-testing:6443",
                "user": "kubeadmin/api-crc-testing:6443",
                "namespace": "default"
            }
        },
        {
            "name": "minishift",
            "context": {
                "cluster": "192-168-42-67:8443",
                "user": "developer/192-168-42-67:8443",
                "namespace": "myproject"
            }
        }
    ],
    "current-context": "default/api-crc-testing:6443/kubeadmin"
} (at console.<anonymous> (/usr/share/code/resources/app/out/vs/workbench/api/node/extensionHostProcess.js:85:94751))
localProcessExtensionHost.ts:298 Extension Host
localProcessExtensionHost.ts:299 {
    "kind": "Config",
    "apiVersion": "v1",
    "preferences": {},
    "clusters": [
        {
            "name": "api-crc-testing:6443",
            "cluster": {
                "server": "https://api.crc.testing:6443",
                "certificate-authority-data": "DATA+OMITTED"
            }
        }
    ],
    "users": [
        {
            "name": "developer",
            "user": {
                "token": "REDACTED"
            }
        },
        {
            "name": "developer/api-crc-testing:6443",
            "user": {
                "token": "REDACTED"
            }
        },
        {
            "name": "kube:admin",
            "user": {
                "token": "REDACTED"
            }
        },
        {
            "name": "kubeadmin",
            "user": {
                "token": "REDACTED"
            }
        },
        {
            "name": "kubeadmin/api-crc-testing:6443",
            "user": {
                "token": "REDACTED"
            }
        }
    ],
    "contexts": [
        {
            "name": "/api-crc-testing:6443/developer",
            "context": {
                "cluster": "api-crc-testing:6443",
                "user": "developer/api-crc-testing:6443"
            }
        },
        {
            "name": "crc-admin",
            "context": {
                "cluster": "api-crc-testing:6443",
                "user": "kubeadmin",
                "namespace": "default"
            }
        },
        {
            "name": "crc-developer",
            "context": {
                "cluster": "api-crc-testing:6443",
                "user": "developer",
                "namespace": "default"
            }
        },
        {
            "name": "default/api-crc-testing:6443/kubeadmin",
            "context": {
                "cluster": "api-crc-testing:6443",
                "user": "kubeadmin/api-crc-testing:6443",
                "namespace": "default"
            }
        },
        {
            "name": "minishift",
            "context": {
                "cluster": "192-168-42-67:8443",
                "user": "developer/192-168-42-67:8443",
                "namespace": "myproject"
            }
        }
    ],
    "current-context": "default/api-crc-testing:6443/kubeadmin"
}
```
</details>

**Comment by apupier** [comment]
in fact with latest kaoto-ui, these elements are no more proposed
